# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'final.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtCore import Qt, QDate, QLocale


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindo")
        MainWindow.resize(1250, 895)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setStyleSheet("#centralwidget{\n"
"background-color:white;\n"
"}")
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_26 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_26.setObjectName("gridLayout_26")
        self.log_out = QtWidgets.QPushButton(self.centralwidget)
        self.log_out.setMaximumSize(QtCore.QSize(300, 16777215))
        self.log_out.setStyleSheet("QPushButton {\n"
"    font-size: 12pt;\n"
"    border-radius: 5px;\n"
"    border: 2px solid rgb(207, 0, 0);\n"
"    color: rgb(170, 0, 0);        \n"
"    padding: 5px 10px;                \n"
"\n"
"}\n"
"QPushButton:hover{\n"
"background-color: rgb(207, 0, 0);\n"
"color: white;\n"
"}")
        self.log_out.setObjectName("log_out")
        self.gridLayout_26.addWidget(self.log_out, 1, 1, 1, 1)
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setMaximumSize(QtCore.QSize(16777215, 1000))
        self.tabWidget.setStyleSheet("QTabWidget::pane {\n"
"    border: none;\n"
"}\n"
"\n"
"QTabBar {\n"
"    qproperty-drawBase: 0;\n"
"    qproperty-expanding: 1;\n"
"}\n"
"\n"
"QTabBar::tab {\n"
"    background: white;\n"
"    color: #444;\n"
"    padding: 10px;\n"
"    font-size: 16px;\n"
"    border: none;\n"
"    border-bottom: 2px solid transparent;\n"
"    width:190px;\n"
"    min-width: 80px;   /* Prevents full collapse */\n"
"    height: 40px;      /* Good click target */\n"
"}\n"
"\n"
"QTabBar::tab:hover {\n"
"    border-bottom: 2px solid #5c9ded;\n"
"}\n"
"\n"
"QTabBar::tab:selected {\n"
"    border-bottom: 2px solid #2c7be5;\n"
"    font-weight: bold;\n"
"    color: #2c7be5;\n"
"}\n"
"background-color:white;\n"
"")
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.gridLayout = QtWidgets.QGridLayout(self.tab)
        self.gridLayout.setObjectName("gridLayout")
        self.savingsrate = QtWidgets.QWidget(self.tab)
        self.savingsrate.setMinimumSize(QtCore.QSize(0, 150))
        self.savingsrate.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.savingsrate.setStyleSheet("#savingsrate{\n"
"background-color: rgb(255, 255, 255);\n"
"border: 2px solid gray;\n"
"border-radius:10px;\n"
"}")
        self.savingsrate.setObjectName("savingsrate")
        self.gridLayout_16 = QtWidgets.QGridLayout(self.savingsrate)
        self.gridLayout_16.setObjectName("gridLayout_16")
        self.label_17 = QtWidgets.QLabel(self.savingsrate)
        self.label_17.setStyleSheet("font-size:15pt;")
        self.label_17.setAlignment(QtCore.Qt.AlignCenter)
        self.label_17.setObjectName("label_17")
        self.gridLayout_16.addWidget(self.label_17, 0, 0, 1, 1)
        self.widget_6 = QtWidgets.QWidget(self.savingsrate)
        self.widget_6.setObjectName("widget_6")
        self.gridLayout_32 = QtWidgets.QGridLayout(self.widget_6)
        self.gridLayout_32.setObjectName("gridLayout_32")
        self.balance = QtWidgets.QLabel(self.widget_6)
        self.balance.setStyleSheet("font-size:15pt;")
        self.balance.setAlignment(QtCore.Qt.AlignCenter)
        self.balance.setObjectName("balance")
        self.gridLayout_32.addWidget(self.balance, 0, 0, 1, 1)
        self.gridLayout_16.addWidget(self.widget_6, 1, 0, 1, 1)
        self.gridLayout.addWidget(self.savingsrate, 0, 2, 1, 1)
        self.monthlyoverview_graph = QtWidgets.QWidget(self.tab)
        self.monthlyoverview_graph.setMinimumSize(QtCore.QSize(0, 300))
        self.monthlyoverview_graph.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.monthlyoverview_graph.setStyleSheet("#monthlyoverview_graph{\n"
"background-color: rgb(255, 255, 255);\n"
"border: 2px solid gray;\n"
"border-radius:10px;\n"
"}")
        self.monthlyoverview_graph.setObjectName("monthlyoverview_graph")
        self.gridLayout_19 = QtWidgets.QGridLayout(self.monthlyoverview_graph)
        self.gridLayout_19.setObjectName("gridLayout_19")
        self.gridLayout.addWidget(self.monthlyoverview_graph, 2, 2, 1, 3)
        self.recenttransactions = QtWidgets.QWidget(self.tab)
        self.recenttransactions.setMaximumSize(QtCore.QSize(16777215, 300))
        self.recenttransactions.setStyleSheet("#recenttransactions{\n"
"background-color: rgb(255, 255, 255);\n"
"border: 2px solid gray;\n"
"border-radius:10px;\n"
"}")
        self.recenttransactions.setObjectName("recenttransactions")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.recenttransactions)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_24 = QtWidgets.QLabel(self.recenttransactions)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_24.sizePolicy().hasHeightForWidth())
        self.label_24.setSizePolicy(sizePolicy)
        self.label_24.setStyleSheet("font-size:18pt;")
        self.label_24.setAlignment(QtCore.Qt.AlignCenter)
        self.label_24.setObjectName("label_24")
        self.verticalLayout.addWidget(self.label_24)
        self.recenttransactionlayout = QtWidgets.QVBoxLayout()
        self.recenttransactionlayout.setObjectName("recenttransactionlayout")
        self.verticalLayout.addLayout(self.recenttransactionlayout)
        self.gridLayout.addWidget(self.recenttransactions, 3, 0, 1, 5)
        self.totalbalance = QtWidgets.QWidget(self.tab)
        self.totalbalance.setMinimumSize(QtCore.QSize(0, 150))
        self.totalbalance.setStyleSheet("#totalbalance{\n"
"background-color: rgb(255, 255, 255);\n"
"border: 2px solid gray;\n"
"border-radius:10px;\n"
"}")
        self.totalbalance.setObjectName("totalbalance")
        self.gridLayout_14 = QtWidgets.QGridLayout(self.totalbalance)
        self.gridLayout_14.setObjectName("gridLayout_14")
        self.widget = QtWidgets.QWidget(self.totalbalance)
        self.widget.setObjectName("widget")
        self.gridLayout_34 = QtWidgets.QGridLayout(self.widget)
        self.gridLayout_34.setObjectName("gridLayout_34")
        self.total_income = QtWidgets.QLabel(self.widget)
        self.total_income.setStyleSheet("font-size:15pt;color:rgb(0, 170, 0)")
        self.total_income.setAlignment(QtCore.Qt.AlignCenter)
        self.total_income.setObjectName("total_income")
        self.gridLayout_34.addWidget(self.total_income, 0, 0, 1, 1)
        self.gridLayout_14.addWidget(self.widget, 1, 0, 1, 1)
        self.label = QtWidgets.QLabel(self.totalbalance)
        self.label.setStyleSheet("font-size:15pt;")
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.gridLayout_14.addWidget(self.label, 0, 0, 1, 1)
        self.gridLayout.addWidget(self.totalbalance, 0, 0, 1, 1)
        self.monthlyincome = QtWidgets.QWidget(self.tab)
        self.monthlyincome.setMinimumSize(QtCore.QSize(0, 150))
        self.monthlyincome.setMaximumSize(QtCore.QSize(16777215, 200))
        self.monthlyincome.setStyleSheet("#monthlyincome{\n"
"background-color: rgb(255, 255, 255);\n"
"border: 2px solid gray;\n"
"border-radius:10px;\n"
"}")
        self.monthlyincome.setObjectName("monthlyincome")
        self.gridLayout_15 = QtWidgets.QGridLayout(self.monthlyincome)
        self.gridLayout_15.setObjectName("gridLayout_15")
        self.widget_2 = QtWidgets.QWidget(self.monthlyincome)
        self.widget_2.setObjectName("widget_2")
        self.gridLayout_33 = QtWidgets.QGridLayout(self.widget_2)
        self.gridLayout_33.setObjectName("gridLayout_33")
        self.average_income = QtWidgets.QLabel(self.widget_2)
        self.average_income.setStyleSheet("font-size:15pt; color:rgb(0, 170, 0);")
        self.average_income.setAlignment(QtCore.Qt.AlignCenter)
        self.average_income.setObjectName("average_income")
        self.gridLayout_33.addWidget(self.average_income, 0, 0, 1, 1)
        self.gridLayout_15.addWidget(self.widget_2, 1, 0, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.monthlyincome)
        self.label_5.setStyleSheet("font-size:15pt;")
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.gridLayout_15.addWidget(self.label_5, 0, 0, 1, 1)
        self.gridLayout.addWidget(self.monthlyincome, 0, 1, 1, 1)
        self.spending_piechart = QtWidgets.QWidget(self.tab)
        self.spending_piechart.setMinimumSize(QtCore.QSize(0, 300))
        self.spending_piechart.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.spending_piechart.setStyleSheet("#spending_piechart{\n"
"background-color: rgb(255, 255, 255);\n"
"border: 2px solid gray;\n"
"border-radius:10px;\n"
"}")
        self.spending_piechart.setObjectName("spending_piechart")
        self.gridLayout_18 = QtWidgets.QGridLayout(self.spending_piechart)
        self.gridLayout_18.setObjectName("gridLayout_18")
        self.gridLayout.addWidget(self.spending_piechart, 2, 0, 1, 2)
        self.monthlyexpenses_2 = QtWidgets.QWidget(self.tab)
        self.monthlyexpenses_2.setMinimumSize(QtCore.QSize(0, 150))
        self.monthlyexpenses_2.setMaximumSize(QtCore.QSize(16777215, 300))
        self.monthlyexpenses_2.setStyleSheet("#monthlyexpenses_2{\n"
"background-color: rgb(255, 255, 255);\n"
"border: 2px solid gray;\n"
"border-radius:10px;\n"
"\n"
"}")
        self.monthlyexpenses_2.setObjectName("monthlyexpenses_2")
        self.gridLayout_22 = QtWidgets.QGridLayout(self.monthlyexpenses_2)
        self.gridLayout_22.setObjectName("gridLayout_22")
        self.label_9 = QtWidgets.QLabel(self.monthlyexpenses_2)
        self.label_9.setStyleSheet("font-size:15pt;")
        self.label_9.setAlignment(QtCore.Qt.AlignCenter)
        self.label_9.setObjectName("label_9")
        self.gridLayout_22.addWidget(self.label_9, 0, 0, 1, 1)
        self.widget_12 = QtWidgets.QWidget(self.monthlyexpenses_2)
        self.widget_12.setObjectName("widget_12")
        self.gridLayout_31 = QtWidgets.QGridLayout(self.widget_12)
        self.gridLayout_31.setObjectName("gridLayout_31")
        self.total_expense = QtWidgets.QLabel(self.widget_12)
        self.total_expense.setStyleSheet("font-size:15pt;color: rgb(170, 0, 0)")
        self.total_expense.setAlignment(QtCore.Qt.AlignCenter)
        self.total_expense.setObjectName("total_expense")
        self.gridLayout_31.addWidget(self.total_expense, 0, 0, 1, 1)
        self.gridLayout_22.addWidget(self.widget_12, 1, 0, 1, 1)
        self.gridLayout.addWidget(self.monthlyexpenses_2, 0, 3, 1, 1)
        self.monthlyexpenses = QtWidgets.QWidget(self.tab)
        self.monthlyexpenses.setMinimumSize(QtCore.QSize(0, 150))
        self.monthlyexpenses.setMaximumSize(QtCore.QSize(16777215, 300))
        self.monthlyexpenses.setStyleSheet("#monthlyexpenses{\n"
"background-color: rgb(255, 255, 255);\n"
"border: 2px solid gray;\n"
"border-radius:10px;\n"
"}")
        self.monthlyexpenses.setObjectName("monthlyexpenses")
        self.gridLayout_17 = QtWidgets.QGridLayout(self.monthlyexpenses)
        self.gridLayout_17.setObjectName("gridLayout_17")
        self.widget_3 = QtWidgets.QWidget(self.monthlyexpenses)
        self.widget_3.setObjectName("widget_3")
        self.gridLayout_30 = QtWidgets.QGridLayout(self.widget_3)
        self.gridLayout_30.setObjectName("gridLayout_30")
        self.average_expense = QtWidgets.QLabel(self.widget_3)
        self.average_expense.setStyleSheet("font-size:15pt;color: rgb(170, 0, 0)")
        self.average_expense.setAlignment(QtCore.Qt.AlignCenter)
        self.average_expense.setObjectName("average_expense")
        self.gridLayout_30.addWidget(self.average_expense, 0, 0, 1, 1)
        self.gridLayout_17.addWidget(self.widget_3, 1, 0, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.monthlyexpenses)
        self.label_8.setStyleSheet("font-size:15pt;")
        self.label_8.setAlignment(QtCore.Qt.AlignCenter)
        self.label_8.setObjectName("label_8")
        self.gridLayout_17.addWidget(self.label_8, 0, 0, 1, 1)
        self.gridLayout.addWidget(self.monthlyexpenses, 0, 4, 1, 1)
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.gridLayout_13 = QtWidgets.QGridLayout(self.tab_2)
        self.gridLayout_13.setObjectName("gridLayout_13")
        self.widget_9 = QtWidgets.QWidget(self.tab_2)
        self.widget_9.setStyleSheet("#widget_9{\n"
"background-color: rgb(255, 255, 255);\n"
"border: 2px solid gray;\n"
"border-radius:10px;\n"
"}")
        self.widget_9.setObjectName("widget_9")
        self.gridLayout_35 = QtWidgets.QGridLayout(self.widget_9)
        self.gridLayout_35.setObjectName("gridLayout_35")
        self.scrollArea_2 = QtWidgets.QScrollArea(self.widget_9)
        self.scrollArea_2.setStyleSheet("")
        self.scrollArea_2.setWidgetResizable(True)
        self.scrollArea_2.setObjectName("scrollArea_2")
        self.budget_area = QtWidgets.QWidget()
        self.budget_area.setGeometry(QtCore.QRect(0, 0, 1194, 453))
        self.budget_area.setAcceptDrops(True)
        self.budget_area.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.budget_area.setObjectName("budget_area")
        self.gridLayout_36 = QtWidgets.QGridLayout(self.budget_area)
        self.gridLayout_36.setObjectName("gridLayout_36")
        self.scrollArea_2.setWidget(self.budget_area)
        self.gridLayout_35.addWidget(self.scrollArea_2, 0, 0, 1, 1)
        self.gridLayout_13.addWidget(self.widget_9, 1, 0, 1, 2)
        self.widget_4 = QtWidgets.QWidget(self.tab_2)
        self.widget_4.setMinimumSize(QtCore.QSize(0, 200))
        self.widget_4.setStyleSheet("#widget_4{\n"
"background-color: rgb(255, 255, 255);\n"
"border: 2px solid gray;\n"
"border-radius:10px;\n"
"}")
        self.widget_4.setObjectName("widget_4")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.widget_4)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.label_10 = QtWidgets.QLabel(self.widget_4)
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(26)
        self.label_10.setFont(font)
        self.label_10.setAlignment(QtCore.Qt.AlignCenter)
        self.label_10.setObjectName("label_10")
        self.verticalLayout_5.addWidget(self.label_10)
        self.budget_amount = QtWidgets.QLineEdit(self.widget_4)
        self.budget_amount.setMinimumSize(QtCore.QSize(0, 50))
        self.budget_amount.setStyleSheet("QLineEdit {\n"
" font-size:15pt;\n"
"    border: 2px solid#c2c2c2 ;\n"
"    border-radius: 10px;\n"
"    padding: 5px;\n"
"}")
        self.budget_amount.setText("")
        self.budget_amount.setObjectName("budget_amount")
        self.verticalLayout_5.addWidget(self.budget_amount)
        self.wrong_amount = QtWidgets.QLabel(self.widget_4)
        self.wrong_amount.setStyleSheet("font-size:13px;background-color:white; color:red; padding-left:3px;")
        self.wrong_amount.setText("")
        self.wrong_amount.setObjectName("wrong_amount")
        self.verticalLayout_5.addWidget(self.wrong_amount)
        self.budget_category = QtWidgets.QComboBox(self.widget_4)
        self.budget_category.setMinimumSize(QtCore.QSize(0, 50))
        self.budget_category.setStyleSheet("\n"
"QComboBox {\n"
"color: rgb(81, 81, 81);\n"
"    font-size:15pt;\n"
"    font-size: 15pt;\n"
"    border: 2px solid #c2c2c2;\n"
"    border-radius: 10px;\n"
"    padding: 5px;\n"
"}")
        self.budget_category.setObjectName("budget_category")
        self.verticalLayout_5.addWidget(self.budget_category)
        self.add_budget = QtWidgets.QPushButton(self.widget_4)
        self.add_budget.setEnabled(True)
        self.add_budget.setStyleSheet("QPushButton {\n"
"    color:white;\n"
"    background-color: rgb(0, 0, 62);\n"
"    font-size:15pt;\n"
"    border: 2px solid #c2c2c2 ;\n"
"    border-radius: 10px;\n"
"    padding: 5px;\n"
"}\n"
"\n"
"#add_budget:pressed{\n"
"    background-color:gray;\n"
"}")
        self.add_budget.setObjectName("add_budget")
        self.verticalLayout_5.addWidget(self.add_budget)
        self.gridLayout_13.addWidget(self.widget_4, 0, 0, 1, 2)
        self.tabWidget.addTab(self.tab_2, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.gridLayout_29 = QtWidgets.QGridLayout(self.tab_3)
        self.gridLayout_29.setObjectName("gridLayout_29")
        self.tabWidget_2 = QtWidgets.QTabWidget(self.tab_3)
        self.tabWidget_2.setStyleSheet("font-size:15pt;\n"
"background-color: rgb(220, 220, 220);")
        self.tabWidget_2.setObjectName("tabWidget_2")
        self.tab_6 = QtWidgets.QWidget()
        self.tab_6.setObjectName("tab_6")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.tab_6)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.widget_5 = QtWidgets.QWidget(self.tab_6)
        self.widget_5.setStyleSheet("#widget_5{\n"
"background-color: rgb(255, 255, 255);\n"
"border: 2px solid gray;\n"
"border-radius:10px;\n"
"}")
        self.widget_5.setObjectName("widget_5")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.widget_5)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label_48 = QtWidgets.QLabel(self.widget_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_48.sizePolicy().hasHeightForWidth())
        self.label_48.setSizePolicy(sizePolicy)
        self.label_48.setStyleSheet("font-size:20pt;background-color:white;")
        self.label_48.setAlignment(QtCore.Qt.AlignCenter)
        self.label_48.setObjectName("label_48")
        self.verticalLayout_4.addWidget(self.label_48)
        self.transaction_add_category = QtWidgets.QComboBox(self.widget_5)
        self.transaction_add_category.setStyleSheet("\n"
"QComboBox {\n"
"color: rgb(81, 81, 81);\n"
"    font-size:15pt;\n"
"    font-size: 15pt;\n"
"    border: 2px solid #c2c2c2;\n"
"    border-radius: 10px;\n"
"    padding: 5px;\n"
"background-color:white;}")
        self.transaction_add_category.setObjectName("transaction_add_category")
        self.transaction_add_category.addItem("")
        self.transaction_add_category.addItem("")
        self.transaction_add_category.addItem("")
        self.transaction_add_category.addItem("")
        self.transaction_add_category.addItem("")
        self.transaction_add_category.addItem("")
        self.transaction_add_category.addItem("")
        self.verticalLayout_4.addWidget(self.transaction_add_category)
        spacerItem = QtWidgets.QSpacerItem(20, 16, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_4.addItem(spacerItem)
        self.transaction_add_type = QtWidgets.QComboBox(self.widget_5)
        self.transaction_add_type.setStyleSheet("\n"
"QComboBox {\n"
"color: rgb(81, 81, 81);\n"
"    font-size:15pt;\n"
"    font-size: 15pt;\n"
"    border: 2px solid #c2c2c2;\n"
"    border-radius: 10px;\n"
"    padding: 5px;\n"
"background-color:white;}")
        self.transaction_add_type.setObjectName("transaction_add_type")
        self.transaction_add_type.addItem("")
        self.transaction_add_type.addItem("")
        self.verticalLayout_4.addWidget(self.transaction_add_type)
        spacerItem1 = QtWidgets.QSpacerItem(20, 16, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_4.addItem(spacerItem1)
        self.transaction_add_amount = QtWidgets.QLineEdit(self.widget_5)
        self.transaction_add_amount.setStyleSheet("QLineEdit {\n"
" font-size:15pt;\n"
"    border: 2px solid#c2c2c2 ;\n"
"    border-radius: 10px;\n"
"    padding: 5px;\n"
"background-color:white;}")
        self.transaction_add_amount.setText("")
        self.transaction_add_amount.setObjectName("transaction_add_amount")
        self.verticalLayout_4.addWidget(self.transaction_add_amount)
        self.transaction_add_wrong_amount = QtWidgets.QLabel(self.widget_5)
        font = QtGui.QFont()
        font.setPointSize(-1)
        self.transaction_add_wrong_amount.setFont(font)
        self.transaction_add_wrong_amount.setStyleSheet("font-size:13px;background-color:white; color:red; padding-left:3px;")
        self.transaction_add_wrong_amount.setText("")
        self.transaction_add_wrong_amount.setObjectName("transaction_add_wrong_amount")
        self.verticalLayout_4.addWidget(self.transaction_add_wrong_amount)
        self.transaction_add_item = QtWidgets.QLineEdit(self.widget_5)
        self.transaction_add_item.setStyleSheet("QLineEdit {\n"
" font-size:15pt;\n"
"    border: 2px solid#c2c2c2 ;\n"
"    border-radius: 10px;\n"
"    padding: 5px;\n"
"background-color:white;}")
        self.transaction_add_item.setText("")
        self.transaction_add_item.setObjectName("transaction_add_item")
        self.verticalLayout_4.addWidget(self.transaction_add_item)
        self.transaction_add_wrong_itemname = QtWidgets.QLabel(self.widget_5)
        self.transaction_add_wrong_itemname.setStyleSheet("font-size:13px;background-color:white; color:red; padding-left:3px;")
        self.transaction_add_wrong_itemname.setText("")
        self.transaction_add_wrong_itemname.setObjectName("transaction_add_wrong_itemname")
        self.verticalLayout_4.addWidget(self.transaction_add_wrong_itemname)
        self.transaction_add_button = QtWidgets.QPushButton(self.widget_5)
        self.transaction_add_button.setStyleSheet("QPushButton {\n"
"    color:white;\n"
"    background-color: rgb(0, 0, 62);\n"
" font-size:12pt;\n"
"    border: 2px solid#c2c2c2 ;\n"
"    border-radius: 10px;\n"
"    padding: 5px;\n"
"}\n"
"#transaction_add_button:pressed{\n"
"    background-color:gray;\n"
"}")
        self.transaction_add_button.setObjectName("transaction_add_button")
        self.verticalLayout_4.addWidget(self.transaction_add_button)
        self.gridLayout_3.addWidget(self.widget_5, 0, 0, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_3.addItem(spacerItem2, 1, 0, 1, 1)
        self.tabWidget_2.addTab(self.tab_6, "")
        self.tab_7 = QtWidgets.QWidget()
        self.tab_7.setObjectName("tab_7")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.tab_7)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.widget_13 = QtWidgets.QWidget(self.tab_7)
        self.widget_13.setMaximumSize(QtCore.QSize(16777215, 150))
        self.widget_13.setStyleSheet("#widget_13{\n"
"background-color: rgb(255, 255, 255);\n"
"border: 2px solid gray;\n"
"border-radius:10px;\n"
"}")
        self.widget_13.setObjectName("widget_13")
        self.gridLayout_21 = QtWidgets.QGridLayout(self.widget_13)
        self.gridLayout_21.setObjectName("gridLayout_21")
        self.label_61 = QtWidgets.QLabel(self.widget_13)
        self.label_61.setStyleSheet("font-size:15pt;\n"
"border-radius: 15px; \n"
"background-color:white;")
        self.label_61.setObjectName("label_61")
        self.gridLayout_21.addWidget(self.label_61, 1, 1, 1, 1)
        self.label_60 = QtWidgets.QLabel(self.widget_13)
        self.label_60.setStyleSheet("font-size:15pt;\n"
"background-color:white;")
        self.label_60.setObjectName("label_60")
        self.gridLayout_21.addWidget(self.label_60, 1, 3, 1, 1)
        self.transaction_category = QtWidgets.QComboBox(self.widget_13)
        self.transaction_category.setStyleSheet("\n"
"QComboBox {\n"
"color: rgb(81, 81, 81);\n"
"    font-size:15pt;\n"
"    font-size: 15pt;\n"
"    border: 2px solid #c2c2c2;\n"
"    border-radius: 10px;\n"
"    padding: 5px;\n"
"background-color:white;\n"
"}")
        self.transaction_category.setObjectName("transaction_category")
        self.transaction_category.addItem("")
        self.transaction_category.addItem("")
        self.transaction_category.addItem("")
        self.transaction_category.addItem("")
        self.transaction_category.addItem("")
        self.transaction_category.addItem("")
        self.transaction_category.addItem("")
        self.gridLayout_21.addWidget(self.transaction_category, 6, 0, 1, 1)
        self.label_58 = QtWidgets.QLabel(self.widget_13)
        self.label_58.setStyleSheet("background-color:white;padding-bottom:10px;")
        self.label_58.setAlignment(QtCore.Qt.AlignCenter)
        self.label_58.setObjectName("label_58")
        self.gridLayout_21.addWidget(self.label_58, 0, 0, 1, 5)
        self.label_62 = QtWidgets.QLabel(self.widget_13)
        self.label_62.setStyleSheet("font-size:15pt; background-color:white;")
        self.label_62.setObjectName("label_62")
        self.gridLayout_21.addWidget(self.label_62, 1, 2, 1, 1)
        self.label_59 = QtWidgets.QLabel(self.widget_13)
        self.label_59.setStyleSheet("font-size:15pt; background-color:white;")
        self.label_59.setObjectName("label_59")
        self.gridLayout_21.addWidget(self.label_59, 1, 0, 1, 1)
        self.to_date = QtWidgets.QDateEdit(self.widget_13)
        self.to_date.setStyleSheet("QDateEdit{\n"
" font-size:15pt;\n"
"    border: 2px solid#c2c2c2 ;\n"
"    border-radius: 10px;\n"
"    padding: 5px;\n"
"background-color:white;\n"
"}")
        self.to_date.setCalendarPopup(True)
        self.to_date.setLocale(QLocale(QLocale.C))
        self.to_date.setDisplayFormat("yyyy-MM-dd")
        self.to_date.setDate(QDate.currentDate())
        self.to_date.setObjectName("to_date")
        self.gridLayout_21.addWidget(self.to_date, 6, 3, 1, 1)
        self.transaction_type = QtWidgets.QComboBox(self.widget_13)
        self.transaction_type.setStyleSheet("\n"
"QComboBox {\n"
"color: rgb(81, 81, 81);\n"
"    font-size:15pt;\n"
"    font-size: 15pt;\n"
"    border: 2px solid #c2c2c2;\n"
"    border-radius: 10px;\n"
"    padding: 5px;\n"
"background-color:white\n"
"}")
        self.transaction_type.setObjectName("transaction_type")
        self.transaction_type.addItem("")
        self.transaction_type.addItem("")
        self.transaction_type.addItem("")
        self.gridLayout_21.addWidget(self.transaction_type, 6, 1, 1, 1)
        self.from_date = QtWidgets.QDateEdit(self.widget_13)
        self.from_date.setStyleSheet("QDateEdit{\n"
" font-size:15pt;\n"
"    border: 2px solid#c2c2c2 ;\n"
"    border-radius: 10px;\n"
"    padding: 5px;\n"
"background-color:white;\n"
"}")
        self.from_date.setCalendarPopup(True)
        self.from_date.setLocale(QLocale(QLocale.C))
        self.from_date.setDisplayFormat("yyyy-MM-dd")
        self.from_date.setDate(QDate.currentDate())
        self.from_date.setObjectName("from_date")
        self.gridLayout_21.addWidget(self.from_date, 6, 2, 1, 1)
        self.transaction_filter_button = QtWidgets.QPushButton(self.widget_13)
        self.transaction_filter_button.setStyleSheet("QPushButton {\n"
"    color:white;\n"
"    background-color: rgb(0, 0, 62);\n"
"     font-size:15pt;\n"
"    border: 2px solid#c2c2c2 ;\n"
"    border-radius: 10px;\n"
"    padding: 5px;\n"
"}\n"
"#transaction_filter_button:pressed{\n"
"    background-color:gray;\n"
"}")
        self.transaction_filter_button.setObjectName("transaction_filter_button")
        self.gridLayout_21.addWidget(self.transaction_filter_button, 6, 4, 1, 1)
        self.gridLayout_4.addWidget(self.widget_13, 0, 0, 1, 1)
        self.recenttransactions_2 = QtWidgets.QWidget(self.tab_7)
        self.recenttransactions_2.setMaximumSize(QtCore.QSize(16777215, 1000))
        self.recenttransactions_2.setStyleSheet("#recenttransactions_2{\n"
"background-color: rgb(255, 255, 255);\n"
"border: 2px solid gray;\n"
"border-radius:10px;\n"
"}")
        self.recenttransactions_2.setObjectName("recenttransactions_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.recenttransactions_2)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_66 = QtWidgets.QLabel(self.recenttransactions_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_66.sizePolicy().hasHeightForWidth())
        self.label_66.setSizePolicy(sizePolicy)
        self.label_66.setStyleSheet("font-size:18pt;background-color:white;")
        self.label_66.setObjectName("label_66")
        self.verticalLayout_2.addWidget(self.label_66)
        self.scrollArea = QtWidgets.QScrollArea(self.recenttransactions_2)
        self.scrollArea.setStyleSheet("background-color:white;")
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.transaction_area = QtWidgets.QWidget()
        self.transaction_area.setGeometry(QtCore.QRect(0, 0, 1176, 448))
        self.transaction_area.setAcceptDrops(True)
        self.transaction_area.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.transaction_area.setObjectName("transaction_area")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.transaction_area)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.scrollArea.setWidget(self.transaction_area)
        self.verticalLayout_2.addWidget(self.scrollArea)
        self.gridLayout_4.addWidget(self.recenttransactions_2, 1, 0, 1, 1)
        self.tabWidget_2.addTab(self.tab_7, "")
        self.gridLayout_29.addWidget(self.tabWidget_2, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tab_3, "")
        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.gridLayout_12 = QtWidgets.QGridLayout(self.tab_4)
        self.gridLayout_12.setObjectName("gridLayout_12")
        self.widget_20 = QtWidgets.QWidget(self.tab_4)
        self.widget_20.setMaximumSize(QtCore.QSize(16777215, 100))
        self.widget_20.setStyleSheet("#widget_20{\n"
"background-color: rgb(255, 255, 255);\n"
"border: 2px solid gray;\n"
"border-radius:15px;\n"
"}")
        self.widget_20.setObjectName("widget_20")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.widget_20)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.label_80 = QtWidgets.QLabel(self.widget_20)
        self.label_80.setStyleSheet("font-size:20pt;")
        self.label_80.setObjectName("label_80")
        self.gridLayout_6.addWidget(self.label_80, 0, 0, 1, 1)
        self.days = QtWidgets.QComboBox(self.widget_20)
        self.days.setStyleSheet("\n"
"QComboBox {\n"
"color: rgb(81, 81, 81);\n"
"    font-size:15pt;\n"
"    font-size: 13pt;\n"
"    border: 2px solid #c2c2c2;\n"
"    border-radius: 10px;\n"
"    padding: 5px;\n"
"}")
        self.days.setObjectName("days")
        self.days.addItem("")
        self.days.addItem("")
        self.days.addItem("")
        self.gridLayout_6.addWidget(self.days, 0, 1, 1, 1)
        self.gridLayout_12.addWidget(self.widget_20, 0, 0, 1, 4)
        self.widget_21 = QtWidgets.QWidget(self.tab_4)
        self.widget_21.setMaximumSize(QtCore.QSize(16777215, 150))
        self.widget_21.setStyleSheet("#widget_21{\n"
"background-color: rgb(255, 255, 255);\n"
"border: 2px solid gray;\n"
"border-radius:15px;\n"
"}")
        self.widget_21.setObjectName("widget_21")
        self.gridLayout_8 = QtWidgets.QGridLayout(self.widget_21)
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.average_income_analytics = QtWidgets.QLabel(self.widget_21)
        self.average_income_analytics.setStyleSheet("font-size:15pt;\n"
"color: rgb(0, 170, 0);")
        self.average_income_analytics.setAlignment(QtCore.Qt.AlignCenter)
        self.average_income_analytics.setObjectName("average_income_analytics")
        self.gridLayout_8.addWidget(self.average_income_analytics, 1, 0, 1, 1)
        self.label_81 = QtWidgets.QLabel(self.widget_21)
        self.label_81.setStyleSheet("font-size:15pt;\n"
"color: black;")
        self.label_81.setAlignment(QtCore.Qt.AlignCenter)
        self.label_81.setObjectName("label_81")
        self.gridLayout_8.addWidget(self.label_81, 0, 0, 1, 1)
        self.gridLayout_12.addWidget(self.widget_21, 1, 0, 1, 1)
        self.widget_25 = QtWidgets.QWidget(self.tab_4)
        self.widget_25.setMaximumSize(QtCore.QSize(16777215, 150))
        self.widget_25.setStyleSheet("#widget_25{\n"
"background-color: rgb(255, 255, 255);\n"
"border: 2px solid gray;\n"
"border-radius:15px;\n"
"}")
        self.widget_25.setObjectName("widget_25")
        self.gridLayout_9 = QtWidgets.QGridLayout(self.widget_25)
        self.gridLayout_9.setObjectName("gridLayout_9")
        self.label_93 = QtWidgets.QLabel(self.widget_25)
        self.label_93.setStyleSheet("font-size:15pt;\n"
"color: black;")
        self.label_93.setAlignment(QtCore.Qt.AlignCenter)
        self.label_93.setObjectName("label_93")
        self.gridLayout_9.addWidget(self.label_93, 0, 0, 1, 1)
        self.average_expense_analytics = QtWidgets.QLabel(self.widget_25)
        self.average_expense_analytics.setStyleSheet("font-size:15pt;\n"
"color: rgb(170, 0, 0);")
        self.average_expense_analytics.setAlignment(QtCore.Qt.AlignCenter)
        self.average_expense_analytics.setObjectName("average_expense_analytics")
        self.gridLayout_9.addWidget(self.average_expense_analytics, 1, 0, 1, 1)
        self.gridLayout_12.addWidget(self.widget_25, 1, 1, 1, 1)
        self.widget_26 = QtWidgets.QWidget(self.tab_4)
        self.widget_26.setMaximumSize(QtCore.QSize(16777215, 150))
        self.widget_26.setStyleSheet("#widget_26{\n"
"background-color: rgb(255, 255, 255);\n"
"border: 2px solid gray;\n"
"border-radius:15px;\n"
"}")
        self.widget_26.setObjectName("widget_26")
        self.gridLayout_10 = QtWidgets.QGridLayout(self.widget_26)
        self.gridLayout_10.setObjectName("gridLayout_10")
        self.total_income_analytics = QtWidgets.QLabel(self.widget_26)
        self.total_income_analytics.setStyleSheet("font-size:15pt;\n"
"color: rgb(0, 170, 0);")
        self.total_income_analytics.setAlignment(QtCore.Qt.AlignCenter)
        self.total_income_analytics.setObjectName("total_income_analytics")
        self.gridLayout_10.addWidget(self.total_income_analytics, 1, 0, 1, 1)
        self.label_96 = QtWidgets.QLabel(self.widget_26)
        self.label_96.setStyleSheet("font-size:15pt;\n"
"color: black;")
        self.label_96.setAlignment(QtCore.Qt.AlignCenter)
        self.label_96.setObjectName("label_96")
        self.gridLayout_10.addWidget(self.label_96, 0, 0, 1, 1)
        self.gridLayout_12.addWidget(self.widget_26, 1, 2, 1, 1)
        self.widget_28 = QtWidgets.QWidget(self.tab_4)
        self.widget_28.setMaximumSize(QtCore.QSize(16777215, 150))
        self.widget_28.setStyleSheet("#widget_28{\n"
"background-color: rgb(255, 255, 255);\n"
"border: 2px solid gray;\n"
"border-radius:15px;\n"
"}")
        self.widget_28.setObjectName("widget_28")
        self.gridLayout_11 = QtWidgets.QGridLayout(self.widget_28)
        self.gridLayout_11.setObjectName("gridLayout_11")
        self.total_expense_analytics = QtWidgets.QLabel(self.widget_28)
        self.total_expense_analytics.setStyleSheet("font-size:15pt;\n"
"color: rgb(170, 0, 0);")
        self.total_expense_analytics.setAlignment(QtCore.Qt.AlignCenter)
        self.total_expense_analytics.setObjectName("total_expense_analytics")
        self.gridLayout_11.addWidget(self.total_expense_analytics, 2, 0, 1, 1)
        self.label_102 = QtWidgets.QLabel(self.widget_28)
        self.label_102.setStyleSheet("font-size:15pt;\n"
"color: black;")
        self.label_102.setAlignment(QtCore.Qt.AlignCenter)
        self.label_102.setObjectName("label_102")
        self.gridLayout_11.addWidget(self.label_102, 0, 0, 1, 1)
        self.gridLayout_12.addWidget(self.widget_28, 1, 3, 1, 1)
        self.analytics_graph = QtWidgets.QWidget(self.tab_4)
        self.analytics_graph.setMinimumSize(QtCore.QSize(0, 500))
        self.analytics_graph.setStyleSheet("#analytics_graph{\n"
"background-color: rgb(255, 255, 255);\n"
"border: 2px solid gray;\n"
"border-radius:15px;\n"
"}")
        self.analytics_graph.setObjectName("analytics_graph")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.analytics_graph)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.gridLayout_12.addWidget(self.analytics_graph, 2, 0, 1, 2)
        self.analytics_piechart = QtWidgets.QWidget(self.tab_4)
        self.analytics_piechart.setStyleSheet("#analytics_piechart{\n"
"background-color: rgb(255, 255, 255);\n"
"border: 2px solid gray;\n"
"border-radius:15px;\n"
"}")
        self.analytics_piechart.setObjectName("analytics_piechart")
        self.analytics_piechart.setMinimumSize(QtCore.QSize(500,0))
        self.gridLayout_20 = QtWidgets.QGridLayout(self.analytics_piechart)
        self.gridLayout_20.setObjectName("gridLayout_20")
        self.gridLayout_12.addWidget(self.analytics_piechart, 2, 2, 1, 2)
        self.tabWidget.addTab(self.tab_4, "")
        self.tab_5 = QtWidgets.QWidget()
        self.tab_5.setObjectName("tab_5")
        self.gridLayout_23 = QtWidgets.QGridLayout(self.tab_5)
        self.gridLayout_23.setObjectName("gridLayout_23")
        self.widget_23 = QtWidgets.QWidget(self.tab_5)
        self.widget_23.setStyleSheet("background-color: white;")
        self.widget_23.setObjectName("widget_23")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.widget_23)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_85 = QtWidgets.QLabel(self.widget_23)
        font = QtGui.QFont()
        font.setPointSize(25)
        font.setBold(True)
        font.setWeight(75)
        self.label_85.setFont(font)
        self.label_85.setStyleSheet("background-color:white;")
        self.label_85.setObjectName("label_85")
        self.gridLayout_2.addWidget(self.label_85, 1, 0, 1, 1)
        self.widget_30 = QtWidgets.QWidget(self.widget_23)
        self.widget_30.setMinimumSize(QtCore.QSize(0, 150))
        self.widget_30.setStyleSheet("#widget_30{\n"
"background-color: rgb(255, 255, 255);\n"
"border: 2px solid gray;\n"
"border-radius:15px;\n"
"}")
        self.widget_30.setObjectName("widget_30")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.widget_30)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.amount_bills = QtWidgets.QLineEdit(self.widget_30)
        self.amount_bills.setMinimumSize(QtCore.QSize(250, 50))
        self.amount_bills.setStyleSheet("QLineEdit {\n"
" font-size:15pt;\n"
"    border: 2px solid#c2c2c2 ;\n"
"    border-radius: 10px;\n"
"    padding: 5px;\n"
"}")
        self.amount_bills.setText("")
        self.amount_bills.setObjectName("amount_bills")
        self.gridLayout_7.addWidget(self.amount_bills, 2, 1, 1, 1)
        self.add_bill = QtWidgets.QPushButton(self.widget_30)
        self.add_bill.setMinimumSize(QtCore.QSize(250, 50))
        self.add_bill.setStyleSheet("QPushButton {\n"
"    color:white;\n"
"    background-color: rgb(0, 0, 62);\n"
" font-size:15pt;\n"
"    border: 2px solid#c2c2c2 ;\n"
"    border-radius: 10px;\n"
"    padding: 5px;\n"
"}")
        self.add_bill.setObjectName("add_bill")
        self.gridLayout_7.addWidget(self.add_bill, 2, 3, 1, 1)
        self.category_bills = QtWidgets.QComboBox(self.widget_30)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.category_bills.sizePolicy().hasHeightForWidth())
        self.category_bills.setSizePolicy(sizePolicy)
        self.category_bills.setMinimumSize(QtCore.QSize(250, 50))
        self.category_bills.setStyleSheet("\n"
"QComboBox {\n"
"color: rgb(81, 81, 81);\n"
"    font-size:15pt;\n"
"    font-size: 15pt;\n"
"    border: 2px solid #c2c2c2;\n"
"    border-radius: 10px;\n"
"    padding: 5px;\n"
"}")
        self.category_bills.setObjectName("category_bills")
        self.category_bills.addItem("")
        self.category_bills.addItem("")
        self.category_bills.addItem("")
        self.category_bills.addItem("")
        self.category_bills.addItem("")
        self.category_bills.addItem("")
        self.category_bills.addItem("")
        self.gridLayout_7.addWidget(self.category_bills, 2, 0, 1, 1)
        self.label_33 = QtWidgets.QLabel(self.widget_30)
        self.label_33.setStyleSheet("font-size:15pt;")
        self.label_33.setObjectName("label_33")
        self.gridLayout_7.addWidget(self.label_33, 1, 2, 1, 1)
        self.date_bills = QtWidgets.QLineEdit(self.widget_30)
        self.date_bills.setMinimumSize(QtCore.QSize(250, 50))
        self.date_bills.setStyleSheet("QLineEdit {\n"
" font-size:15pt;\n"
"    border: 2px solid#c2c2c2 ;\n"
"    border-radius: 10px;\n"
"    padding: 5px;\n"
"}")
        self.date_bills.setText("")
        self.date_bills.setObjectName("date_bills")
        self.gridLayout_7.addWidget(self.date_bills, 2, 2, 1, 1)
        self.label_14 = QtWidgets.QLabel(self.widget_30)
        self.label_14.setStyleSheet("font-size:15pt;")
        self.label_14.setObjectName("label_14")
        self.gridLayout_7.addWidget(self.label_14, 1, 0, 1, 1)
        self.label_15 = QtWidgets.QLabel(self.widget_30)
        self.label_15.setStyleSheet("font-size:15pt;")
        self.label_15.setObjectName("label_15")
        self.gridLayout_7.addWidget(self.label_15, 1, 1, 1, 1)
        self.wrong_amount_bills = QtWidgets.QLabel(self.widget_30)
        self.wrong_amount_bills.setStyleSheet("font-size:13px;background-color:white; color:red; padding-left:3px;")
        self.wrong_amount_bills.setAlignment(Qt.AlignHCenter)
        self.wrong_amount_bills.setText("")
        self.wrong_amount_bills.setObjectName("wrong_amount_bills")
        self.gridLayout_7.addWidget(self.wrong_amount_bills, 3, 1, 1, 2)
        self.label_13 = QtWidgets.QLabel(self.widget_30)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_13.setFont(font)
        self.label_13.setAlignment(QtCore.Qt.AlignCenter)
        self.label_13.setObjectName("label_13")
        self.gridLayout_7.addWidget(self.label_13, 0, 0, 1, 4)
        self.gridLayout_2.addWidget(self.widget_30, 0, 0, 1, 1)
        self.scrollArea_3 = QtWidgets.QScrollArea(self.widget_23)
        self.scrollArea_3.setWidgetResizable(True)
        self.scrollArea_3.setObjectName("scrollArea_3")
        self.bills_scroll = QtWidgets.QWidget()
        self.bills_scroll.setGeometry(QtCore.QRect(0, 0, 1194, 494))
        self.bills_scroll.setObjectName("scrollAreaWidgetContents")
        self.gridLayout_24 = QtWidgets.QGridLayout(self.bills_scroll)
        self.gridLayout_24.setObjectName("gridLayout_24")
        self.scrollArea_3.setWidget(self.bills_scroll)
        self.gridLayout_2.addWidget(self.scrollArea_3, 2, 0, 1, 1)
        self.gridLayout_23.addWidget(self.widget_23, 0, 0, 2, 2)
        self.tabWidget.addTab(self.tab_5, "")
        self.gridLayout_26.addWidget(self.tabWidget, 2, 1, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1250, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        self.tabWidget_2.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.log_out.setText(_translate("MainWindow", "Log out"))
        self.label_17.setText(_translate("MainWindow", "    Balance   "))
        self.balance.setText(_translate("MainWindow", "$2,850.00"))
        self.label_24.setText(_translate("MainWindow", "Recent Transactions"))
        self.total_income.setText(_translate("MainWindow", "$12,450.00"))
        self.label.setText(_translate("MainWindow", "Total income"))
        self.average_income.setText(_translate("MainWindow", "$4,200.00"))
        self.label_5.setText(_translate("MainWindow", "Average Income"))
        self.label_9.setText(_translate("MainWindow", "Total  Expenses"))
        self.total_expense.setText(_translate("MainWindow", "$2,850.00"))
        self.average_expense.setText(_translate("MainWindow", "$2,850.00"))
        self.label_8.setText(_translate("MainWindow", "Average Expense"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "dashboard"))
        self.label_10.setText(_translate("MainWindow", "Add new budget"))
        self.budget_amount.setPlaceholderText(_translate("MainWindow", "Enter amount"))
        self.add_budget.setText(_translate("MainWindow", "Add Budget"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "budget"))
        self.label_48.setText(_translate("MainWindow", "Add new transaction"))
        self.transaction_add_category.setItemText(0, _translate("MainWindow", "Select category "))
        self.transaction_add_category.setItemText(1, _translate("MainWindow", "Food And Dining"))
        self.transaction_add_category.setItemText(2, _translate("MainWindow", "Transportation"))
        self.transaction_add_category.setItemText(3, _translate("MainWindow", "Entertainment"))
        self.transaction_add_category.setItemText(4, _translate("MainWindow", "Utilities"))
        self.transaction_add_category.setItemText(5, _translate("MainWindow", "Healthcare"))
        self.transaction_add_category.setItemText(6, _translate("MainWindow", "Shopping"))
        self.transaction_add_type.setItemText(0, _translate("MainWindow", "Income"))
        self.transaction_add_type.setItemText(1, _translate("MainWindow", "Expense"))
        self.transaction_add_amount.setPlaceholderText(_translate("MainWindow", "Enter amount"))
        self.transaction_add_item.setPlaceholderText(_translate("MainWindow", "Enter Item"))
        self.transaction_add_button.setText(_translate("MainWindow", "Add Transaction"))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_6), _translate("MainWindow", "                          Add Transaction             "))
        self.label_61.setText(_translate("MainWindow", "Type"))
        self.label_60.setText(_translate("MainWindow", "To Date"))
        self.transaction_category.setItemText(0, _translate("MainWindow", "Select category "))
        self.transaction_category.setItemText(1, _translate("MainWindow", "Food And Dining"))
        self.transaction_category.setItemText(2, _translate("MainWindow", "Transportation"))
        self.transaction_category.setItemText(3, _translate("MainWindow", "Entertainment"))
        self.transaction_category.setItemText(4, _translate("MainWindow", "Utilities"))
        self.transaction_category.setItemText(5, _translate("MainWindow", "Healthcare"))
        self.transaction_category.setItemText(6, _translate("MainWindow", "Shopping"))
        self.label_58.setText(_translate("MainWindow", "Filter Transactions"))
        self.label_62.setText(_translate("MainWindow", "From Date"))
        self.label_59.setText(_translate("MainWindow", "Category"))
        self.to_date.setDisplayFormat(_translate("MainWindow", "yyyy-MM-dd"))
        self.transaction_type.setItemText(0, _translate("MainWindow", "All"))
        self.transaction_type.setItemText(1, _translate("MainWindow", "Income"))
        self.transaction_type.setItemText(2, _translate("MainWindow", "Expense"))
        self.from_date.setDisplayFormat(_translate("MainWindow", "yyyy-MM-dd"))
        self.transaction_filter_button.setText(_translate("MainWindow", "Filter"))
        self.label_66.setText(_translate("MainWindow", " Transactions"))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_7), _translate("MainWindow", "                 View and Filter                 "))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("MainWindow", "transactions"))
        self.label_80.setText(_translate("MainWindow", "Analytics Overview"))
        self.days.setItemText(0, _translate("MainWindow", "Last 30 Days"))
        self.days.setItemText(1, _translate("MainWindow", "Last 60 Days"))
        self.days.setItemText(2, _translate("MainWindow", "Last 90 Days"))
        self.average_income_analytics.setText(_translate("MainWindow", "$4200.00"))
        self.label_81.setText(_translate("MainWindow", "Average Income"))
        self.label_93.setText(_translate("MainWindow", "Average Expenses"))
        self.average_expense_analytics.setText(_translate("MainWindow", "$892"))
        self.total_income_analytics.setText(_translate("MainWindow", "$21,900"))
        self.label_96.setText(_translate("MainWindow", "Total Income"))
        self.total_expense_analytics.setText(_translate("MainWindow", "$20000"))
        self.label_102.setText(_translate("MainWindow", "Total Expenses"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_4), _translate("MainWindow", "analytics"))
        self.label_85.setText(_translate("MainWindow", "Recurring bills"))
        self.amount_bills.setPlaceholderText(_translate("MainWindow", "Enter amount"))
        self.add_bill.setText(_translate("MainWindow", "Add Bill"))
        self.category_bills.setItemText(0, _translate("MainWindow", "Select category "))
        self.category_bills.setItemText(1, _translate("MainWindow", "Food And Dining"))
        self.category_bills.setItemText(2, _translate("MainWindow", "Transportation"))
        self.category_bills.setItemText(3, _translate("MainWindow", "Entertainment"))
        self.category_bills.setItemText(4, _translate("MainWindow", "Utilities"))
        self.category_bills.setItemText(5, _translate("MainWindow", "Healthcare"))
        self.category_bills.setItemText(6, _translate("MainWindow", "Shopping"))
        self.label_33.setText(_translate("MainWindow", "Date"))
        self.date_bills.setPlaceholderText(_translate("MainWindow", "Enter Date"))
        self.label_14.setText(_translate("MainWindow", "Category"))
        self.label_15.setText(_translate("MainWindow", "Price"))
        self.label_13.setText(_translate("MainWindow", "Add new Bills"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_5), _translate("MainWindow", "Bills"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
