# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'transaction_frame.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class TransactionFrame(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(876, 300)
        self.gridLayout = QtWidgets.QGridLayout(Form)
        self.gridLayout.setObjectName("gridLayout")
        self.transaction_frame = QtWidgets.QWidget(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.transaction_frame.sizePolicy().hasHeightForWidth())
        self.transaction_frame.setSizePolicy(sizePolicy)
        self.transaction_frame.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.transaction_frame.setStyleSheet("#transaction_frame{\n"
"border:2px solid gray;\n"
"border-radius:10px;\n"
"background-color:white;\n"
"}")
        self.transaction_frame.setObjectName("transaction_frame")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.transaction_frame)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label = QtWidgets.QLabel(self.transaction_frame)
        self.label.setStyleSheet("font-size:12pt;")
        self.label.setObjectName("label")
        self.horizontalLayout_2.addWidget(self.label)
        self.category = QtWidgets.QLabel(self.transaction_frame)
        self.category.setStyleSheet("font-size:12pt")
        self.category.setAlignment(QtCore.Qt.AlignCenter)
        self.category.setObjectName("category")
        self.horizontalLayout_2.addWidget(self.category)
        self.date = QtWidgets.QLabel(self.transaction_frame)
        self.date.setStyleSheet("color:gray;font-size:10pt")
        self.date.setAlignment(QtCore.Qt.AlignCenter)
        self.date.setObjectName("date")
        self.horizontalLayout_2.addWidget(self.date)
        self.price = QtWidgets.QLabel(self.transaction_frame)
        self.price.setStyleSheet("font-size:12pt;\n"
"\n"
"color: rgb(170, 0, 0);")
        self.price.setAlignment(QtCore.Qt.AlignCenter)
        self.price.setObjectName("price")
        self.horizontalLayout_2.addWidget(self.price)
        self.transaction_remove = QtWidgets.QPushButton(self.transaction_frame)
        self.transaction_remove.setMaximumSize(QtCore.QSize(150, 50))
        self.transaction_remove.setStyleSheet("QPushButton {\n"
"    font-size: 15pt;\n"
"    border-radius: 5px;\n"
"    border: 2px solid rgb(207, 0, 0);\n"
"    color: rgb(170, 0, 0);        \n"
"    padding: 5px 10px;                \n"
"\n"
"}\n"
"QPushButton:hover{\n"
"background-color: rgb(207, 0, 0);\n"
"color: white;\n"
"\n"
"}")
        self.transaction_remove.setObjectName("transaction_remove")
        self.horizontalLayout_2.addWidget(self.transaction_remove)
        self.label.raise_()
        self.transaction_remove.raise_()
        self.category.raise_()
        self.date.raise_()
        self.price.raise_()
        self.gridLayout.addWidget(self.transaction_frame, 0, 0, 1, 1)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label.setText(_translate("Form", "Gas Station"))
        self.category.setText(_translate("Form", "category"))
        self.date.setText(_translate("Form", "date"))
        self.price.setText(_translate("Form", "$45.00"))
        self.transaction_remove.setText(_translate("Form", "Remove"))
