# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'bills_frame.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class BillsFrame(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(400, 300)
        self.gridLayout = QtWidgets.QGridLayout(Form)
        self.gridLayout.setObjectName("gridLayout")
        self.bill_frame = QtWidgets.QWidget(Form)
        self.bill_frame.setMinimumSize(QtCore.QSize(0, 0))
        self.bill_frame.setMaximumSize(QtCore.QSize(300, 200))
        self.bill_frame.setStyleSheet("#bill_frame{\n"
"background-color: rgb(255, 255, 255);\n"
"border: 2px solid gray;\n"
"border-radius:15px;\n"
"} ")
        self.bill_frame.setObjectName("bill_frame")
        self.gridLayout_25 = QtWidgets.QGridLayout(self.bill_frame)
        self.gridLayout_25.setObjectName("gridLayout_25")
        self.bills_label = QtWidgets.QLabel(self.bill_frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bills_label.sizePolicy().hasHeightForWidth())
        self.bills_label.setSizePolicy(sizePolicy)
        self.bills_label.setStyleSheet("font-size:18pt;\n"
"color: rgb(0, 0, 0);\n"
"background-color:white")
        self.bills_label.setAlignment(QtCore.Qt.AlignCenter)
        self.bills_label.setObjectName("bills_label")
        self.gridLayout_25.addWidget(self.bills_label, 0, 0, 1, 2)
        self.remove_bills = QtWidgets.QPushButton(self.bill_frame)
        self.remove_bills.setStyleSheet("QPushButton {\n"
"    font-size: 15pt;\n"
"    border-radius: 5px;\n"
"    border: 2px solid rgb(207, 0, 0);\n"
"    color: rgb(170, 0, 0);        \n"
"    padding: 5px 10px;    \n"
"    background-color:white            \n"
"}\n"
"QPushButton:hover{\n"
"background-color: rgb(207, 0, 0);\n"
"color: white;\n"
"}")
        self.remove_bills.setObjectName("remove_bills")
        self.gridLayout_25.addWidget(self.remove_bills, 4, 1, 1, 1)
        self.price = QtWidgets.QLabel(self.bill_frame)
        self.price.setStyleSheet("font-size:15pt;\n"
"color: rgb(0, 0, 0);background-color:white")
        self.price.setObjectName("price")
        self.gridLayout_25.addWidget(self.price, 2, 0, 1, 1)
        self.Day = QtWidgets.QLabel(self.bill_frame)
        self.Day.setStyleSheet("font-size:10pt;\n"
"color: rgb(138, 138, 138);background-color:white")
        self.Day.setObjectName("Day")
        self.gridLayout_25.addWidget(self.Day, 4, 0, 1, 1)
        self.gridLayout.addWidget(self.bill_frame, 0, 0, 1, 1)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.bills_label.setText(_translate("Form", "⚡️Electric Bill"))
        self.remove_bills.setText(_translate("Form", "Remove"))
        self.price.setText(_translate("Form", "$127.45"))
        self.Day.setText(_translate("Form", "Day: 25"))
