# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'recent transactions frame.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class RecentTransactions(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1055, 113)
        self.verticalLayout = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout.setObjectName("verticalLayout")
        self.widget_11 = QtWidgets.QWidget(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_11.sizePolicy().hasHeightForWidth())
        self.widget_11.setSizePolicy(sizePolicy)
        self.widget_11.setMinimumSize(QtCore.QSize(16777215, 70))
        self.widget_11.setMaximumSize(QtCore.QSize(16777215, 200))
        self.widget_11.setStyleSheet("#widget_11{\n"
"border:2px solid gray;\n"
"border-radius:10px\n"
"}")
        self.widget_11.setObjectName("widget_11")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget_11)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.itemname = QtWidgets.QLabel(self.widget_11)
        self.itemname.setStyleSheet("font-size:12pt;")
        self.itemname.setObjectName("itemname")
        self.horizontalLayout.addWidget(self.itemname)
        self.category = QtWidgets.QLabel(self.widget_11)
        self.category.setStyleSheet("font-size:12pt;")
        self.category.setObjectName("category")
        self.horizontalLayout.addWidget(self.category)
        self.date = QtWidgets.QLabel(self.widget_11)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.date.setFont(font)
        self.date.setStyleSheet("font-size:10pt;\n"
"color: rgb(177, 177, 177)")
        self.date.setAlignment(QtCore.Qt.AlignCenter)
        self.date.setObjectName("date")
        self.horizontalLayout.addWidget(self.date)
        self.price = QtWidgets.QLabel(self.widget_11)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.price.sizePolicy().hasHeightForWidth())
        self.price.setSizePolicy(sizePolicy)
        self.price.setStyleSheet("font-size:12pt;\n"
"\n"
"color: rgb(170, 0, 0);")
        self.price.setAlignment(QtCore.Qt.AlignCenter)
        self.price.setObjectName("price")
        self.horizontalLayout.addWidget(self.price)
        self.verticalLayout.addWidget(self.widget_11)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.itemname.setText(_translate("Form", "Electric Bill"))
        self.category.setText(_translate("Form", "Category"))
        self.date.setText(_translate("Form", "2024-01-13"))
        self.price.setText(_translate("Form", "$85.00"))
