# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'budgetframe.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QLabel, QSizePolicy


class BudgetFrame(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(400, 300)
        self.gridLayout = QtWidgets.QGridLayout(Form)
        self.gridLayout.setObjectName("gridLayout")
        self.frame_2 = QtWidgets.QFrame(Form)
        self.frame_2.setMinimumSize(QtCore.QSize(300, 200))
        self.frame_2.setMaximumSize(QtCore.QSize(300, 200))
        self.frame_2.setStyleSheet("#frame_2{\n"
"background-color: rgb(255, 255, 255);\n"
"border: 2px solid gray;\n"
"border-radius:10px;\n"
"\n"
"}")
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.frame_2)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.progressbar = QtWidgets.QProgressBar(self.frame_2)
        self.progressbar.setStyleSheet("QProgressBar{\n"
"    background-color: rgb(200, 200, 200);\n"
"border-style:solid;\n"
"font-size:15pt;\n"
"border-radius:10px;\n"
"text-visible:false;\n"
"}\n"
"QProgressBar::chunk{\n"
"border-radius: 10px;\n"
"background-color: rgb(0, 0, 62);\n"
"}\n"
"")
        self.progressbar.setProperty("value", 65)
        self.progressbar.setTextVisible(False)
        self.progressbar.setObjectName("progressbar")
        self.gridLayout_5.addWidget(self.progressbar, 2, 0, 1, 2)
        self.remove_budget = QtWidgets.QPushButton(self.frame_2)
        self.remove_budget.setStyleSheet("QPushButton {\n"
"    font-size: 15pt;\n"
"    border-radius: 5px;\n"
"    border: 2px solid rgb(207, 0, 0);\n"
"    color: rgb(170, 0, 0);        \n"
"    padding: 5px 10px;                \n"
"\n"
"}\n"
"QPushButton:hover{\n"
"background-color: rgb(207, 0, 0);\n"
"color: white;\n"
"}")
        self.remove_budget.setObjectName("remove_budget")
        self.gridLayout_5.addWidget(self.remove_budget, 0, 1, 1, 1)
        self.budget = QtWidgets.QLabel(self.frame_2)
        self.budget.setStyleSheet("font-size:10pt;\n"
"color: rgb(81, 81, 81);")
        self.budget.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.budget.setObjectName("budget")
        self.gridLayout_5.addWidget(self.budget, 1, 1, 1, 1)
        self.spent = QtWidgets.QLabel(self.frame_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.spent.sizePolicy().hasHeightForWidth())
        self.spent.setSizePolicy(sizePolicy)
        self.spent.setStyleSheet("font-size:10pt;\n"
"color: rgb(81, 81, 81);\n"
"\n"
"")
        self.spent.setObjectName("spent")
        self.gridLayout_5.addWidget(self.spent, 1, 0, 1, 1)
        self.label = QtWidgets.QLabel(self.frame_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(QSizePolicy.Minimum, QSizePolicy.Maximum)
        self.label.setMaximumSize(QtCore.QSize(16777215, 33))
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.label.setStyleSheet("font-size:20pt;")
        self.gridLayout_5.addWidget(self.label, 0, 0, 1, 1)
        self.status = QtWidgets.QLabel(self.frame_2)
        self.status.setStyleSheet("font-size:10pt;\n"
"color: rgb(81, 81, 81);\n"
"\n"
"")
        self.remove_budget.setSizePolicy(QSizePolicy.Maximum, QSizePolicy.Preferred)
        
        self.status.setAlignment(QtCore.Qt.AlignCenter)
        self.status.setObjectName("status")
        self.gridLayout_5.addWidget(self.status, 3, 0, 1, 2)
        self.gridLayout.addWidget(self.frame_2, 0, 0, 1, 1)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.remove_budget.setText(_translate("Form", "Remove"))
        self.budget.setText(_translate("Form", "Budget: $800"))
        self.spent.setText(_translate("Form", "Spent: $520"))
        self.label.setText(_translate("Form", "Food & Dining\n"
""))
        self.status.setText(_translate("Form", "Status:You Are Under Budget By $500"))
